const productTypes = [
    'Corn',
    'Onion',
    'Garlic',
    'Eggplant',
    'Mango',
    'Tomato',
    'Broccoli',
    'Carrot',
    'Asparagus',
    'Cauliflower',
    'Cucumber',
    'Green beans',
    'Lettuce',
    'Mushroom',
    'Bell Pepper',
    'Spinach',
    'Sweet Potato',
    'Cabbage',
    'Okra',
    'Pumpkin',
    'Radish',
    'Apple',
    'Avocado',
    'Banana',
    'Guava',
    'Kiwi',
    'Lemon',
    'Pineapple',
    'Watermelon',
    'Cantaloupe',
    'Jackfruit',
    'Potato',
    'Mushroom'
].sort()

export default productTypes
